build/app.js: index.js lib/activator.js lib/server-connector.js lib/script-connector.js
	@component build --name app --standalone app
	@echo build build/app.js

clean:
	rm -fr build components

.PHONY: clean
